name: pulumi-gke
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - nodejs
  - google-cloud-sdk
  - pip:
      - pulumi
      - pulumi-gcp
      - pulumi-docker
      - pulumi-kubernetes
