name: 'Deploy to Google Cloud with Pulumi'

on:
  push:
    branches:
      - main

env:
  REGION: 'europe-west1'  # TODO: update to your region

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Step 2: Authenticate with Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/githuboauthpool/providers/githuboauth-provider'
          service_account: 'githubactions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      # Step 3: Set up the Pulumi CLI
      - name: 'Install Pulumi CLI'
        uses: 'pulumi/actions-install-pulumi-cli@v3.0.0'

      # Step 4: Install Python dependencies (assuming a Python Pulumi project)
      - name: 'Install Python Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Log in to Pulumi
      - name: 'Pulumi Login'
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Step 6: Pulumi Preview (optional, to see what changes will be made)
      - name: 'Pulumi Preview'
        run: pulumi preview

      # Step 7: Pulumi Update (deploy the infrastructure)
      - name: 'Pulumi Up'
        run: pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
