name: 'Deploy to Google Cloud with Pulumi'

on:
  push:
    branches:
      - main

env:
  REGION: 'europe-west10'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Step 2: Authenticate with Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/githuboauthpool/providers/githuboauth-provider'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}'

      # Step 3: Install Pulumi CLI
      - name: 'Install Pulumi CLI'
        uses: 'pulumi/actions@v5'
        with:
          pulumi-version: 'latest'

      # Step 3a: Install Google Cloud SDK
      - name: 'Install Google Cloud SDK and GKE Auth Plugin'
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get install apt-transport-https ca-certificates gnupg -y
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
          # Fix missing GPG key error
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0BA5CE6DC6315A3
          sudo apt-get update && sudo apt-get install google-cloud-sdk google-cloud-cli-gke-gcloud-auth-plugin -y

      # Step 4: Install dependencies (for Python or any other package management)
      - name: 'Install Python Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Pulumi Refresh (ensures Pulumi state is up to date)
      - name: 'Pulumi Refresh'
        uses: 'pulumi/actions@v5'
        with:
          command: refresh
          stack-name: 'qcserestipy/dev'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # Step 6: Pulumi Preview (optional)
      - name: 'Pulumi Preview'
        uses: 'pulumi/actions@v5'
        with:
          command: preview
          stack-name: 'qcserestipy/dev'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # Step 7: Pulumi Up (deploy the infrastructure)
      - name: 'Pulumi Up'
        uses: 'pulumi/actions@v5'
        with:
          command: up
          stack-name: 'qcserestipy/dev'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
