name: 'Deploy to Google Cloud with Pulumi'

on:
  push:
    branches:
      - main

env:
  REGION: 'us-central1'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Step 2: Authenticate with Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/githuboauthpool/providers/githuboauth-provider'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}'

      # Step 3: Install Pulumi CLI
      - name: 'Install Pulumi CLI'
        uses: 'pulumi/actions@v5'
        with:
          pulumi-version: 'latest'

      # Step 4: Install dependencies (for Python or any other package management)
      - name: 'Install Python Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Pulumi Preview (optional)
      - name: 'Pulumi Preview'
        uses: 'pulumi/actions@v5'
        with:
          command: preview
          stack-name: 'qcserestipy/dev'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # Step 6: Pulumi Up (deploy the infrastructure)
      - name: 'Pulumi Up'
        uses: 'pulumi/actions@v5'
        with:
          command: up
          stack-name: 'qcserestipy/dev'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
